---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: ita
- type: directory
  path: content/posts-it
  label: Posts
  create: all
  match: "**/*"
  new_doc_ext: ".ita.md"
  templates:
  - post
- type: heading
  label: eng
- type: directory
  path: content/posts-en
  label: Posts
  create: all
  match: "**/*"
  new_doc_ext: en.md
  templates:
  - post
- type: directory
  path: content/home
  label: Home
  create: none
  match: "*"
- type: directory
  path: content/guides
  label: Guides
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: none
  match: "*"
- type: directory
  path: data
  label: Data
  create: documents
  match: "*"
  new_doc_ext: yml
- type: directory
  path: content/contact
  label: Contact
  create: none
  match: "*"
- type: document
  path: config.toml
  label: Configuration
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.81.0
